// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dao

// Injectors from wire.go:

//go:generate kratos tool wire
func newTestDao() (Dao, func(), error) {
	db, cleanup, err := NewDB()
	if err != nil {
		return nil, nil, err
	}
	daoDao, cleanup2, err := New(db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return daoDao, func() {
		cleanup2()
		cleanup()
	}, nil
}
